version: "3.7"
services:

    #----------------------------------------------------------------------------------------
    zookeeper-7.6.0-security:
        env_file: .env
        image: confluentinc/cp-zookeeper:7.6.0
        container_name: zookeeper-7.6.0-security
        ports:
            - ${CUSTOM_ZOOKEEPER_PORT}:2181
        environment:
            #ALLOW_ANONYMOUS_LOGIN: "yes"
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

            ### => Security
            ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
            ZOOKEEPER_REQUIRE_CLIENT_AUTH_SCHEME: SASL
            JVMFLAGS: "-Djava.security.auth.login.config=/etc/zookeeper/zookeeper_jaas.conf"
            JAVA_TOOL_OPTIONS: "-Djava.security.auth.login.config=/etc/zookeeper/zookeeper_jaas.conf"
        volumes:
            - zookeeper_vol_security:/zookeeper/
            - ./shared/:/home/shared/
            - ./security/zookeeper_jaas.conf:/etc/zookeeper/zookeeper_jaas.conf
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------
    kafka-7.6.0-security:
        env_file: .env
        image: confluentinc/cp-kafka:7.6.0
        container_name: kafka-7.6.0-security
        ports:
            - ${CUSTOM_KAFKA_PORT}:9092
            - ${CUSTOM_KAFKA_EXTERNAL_PORT}:9094
        environment:
            ### => Broker settings
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_SET_ACL: "true"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper-7.6.0-security:2181

            ### => Authentication Implements => SASL/PLAIN
            KAFKA_LISTENERS: SASL_PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094
            KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://kafka-7.6.0-security:9092,EXTERNAL://localhost:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SASL_PLAINTEXT:SASL_PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT

            ### => Define the mechanism of authentication SASL
            KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
            KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN

            ### => Create users
            KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/server_jaas.conf"
            JAVA_TOOL_OPTIONS: "-Djava.security.auth.login.config=/etc/kafka/server_jaas.conf"

            ### => Credentials
            CUSTOM_KAFKA_DEFAULT_USER: ${CUSTOM_KAFKA_DEFAULT_USER}
            CUSTOM_KAFKA_DEFAULT_PASS: ${CUSTOM_KAFKA_DEFAULT_PASS}
            CUSTOM_KAFKA_DEFAULT_APP_USER: ${CUSTOM_KAFKA_DEFAULT_APP_USER}
        privileged: true
        tty: true
        volumes:
            - kafka_vol_security:/kafka/
            - ./shared/:/home/shared/
            - ./security/server_jaas.conf:/etc/kafka/server_jaas.conf
        depends_on:
            - zookeeper-7.6.0-security
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------
    kafka-ui-0.7.2:
        env_file: .env
        image: provectuslabs/kafka-ui:v0.7.2
        container_name: kafka-ui-0.7.2
        ports:
            - ${CUSTOM_KAFKA_UI_PORT}:8080
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-7.6.0-security:9092
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-7.6.0-security:2181

            ### => SASL credentials
            KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
            KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
            KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="${CUSTOM_KAFKA_DEFAULT_USER}" password="${CUSTOM_KAFKA_DEFAULT_PASS}";

            ### => Form Login Authentication
            AUTH_TYPE: LOGIN_FORM
            SPRING_SECURITY_USER_NAME: ${CUSTOM_KAFKA_UI_LOGIN_USER}
            SPRING_SECURITY_USER_PASSWORD: ${CUSTOM_KAFKA_UI_LOGIN_PASS}
        privileged: true
        tty: true
        volumes:
            - kafka_ui_vol_security:/kafka-ui/
            - ./shared/:/home/shared/
        depends_on:
            - kafka-7.6.0-security
            - zookeeper-7.6.0-security
        networks:
            - default
            - open_network
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true

volumes:
    kafka_vol_security:
    kafka_ui_vol_security:
    zookeeper_vol_security:

