version: "3.7"
services:

    #----------------------------------------------------------------------------------------
    zookeeper-7.6.0-v2:
        image: confluentinc/cp-zookeeper:7.6.0
        hostname: zookeeper-7.6.0-v2
        container_name: zookeeper-7.6.0-v2
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
    #----------------------------------------------------------------------------------------
    broker-7.6.0-v2:
        image: confluentinc/cp-kafka:7.6.0
        hostname: broker-7.6.0-v2
        container_name: broker-7.6.0-v2
        depends_on:
            - zookeeper-7.6.0-v2
        ports:
            - "29092:29092"
            - "9092:9092"
            - "9101:9101"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-7.6.0-v2:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-7.6.0-v2:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_JMX_PORT: 9101
    #----------------------------------------------------------------------------------------
    schema-registry-7.6.0-v2:
        image: confluentinc/cp-schema-registry:7.6.0
        hostname: schema-registry-7.6.0-v2
        container_name: schema-registry-7.6.0-v2
        depends_on:
            - zookeeper-7.6.0-v2
            - broker-7.6.0-v2
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry-7.6.0-v2
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://broker-7.6.0-v2:29092'
            SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
    #----------------------------------------------------------------------------------------
    rest-proxy-7.6.0-v2:
        image: confluentinc/cp-kafka-rest:7.6.0
        depends_on:
            - zookeeper-7.6.0-v2
            - broker-7.6.0-v2
            - schema-registry-7.6.0-v2
        ports:
            - "8082:8082"
        hostname: rest-proxy-7.6.0-v2
        container_name: rest-proxy-7.6.0-v2
        environment:
            KAFKA_REST_HOST_NAME: rest-proxy-7.6.0-v2
            KAFKA_REST_BOOTSTRAP_SERVERS: 'broker-7.6.0-v2:29092'
            KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
            KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry-7.6.0-v2:8081'
        volumes:
            - rest-proxy_7.6.0-v2_vol:/var/lib/kafka-rest/data
    #----------------------------------------------------------------------------------------
    control-center-5.4.0:
        image: confluentinc/cp-enterprise-control-center:5.4.0
        hostname: control-center-7.6.0-v2
        container_name: control-center-7.6.0-v2
        depends_on:
            - zookeeper-7.6.0-v2
            - broker-7.6.0-v2
            - schema-registry-7.6.0-v2
        ports:
            - "9021:9021"
        environment:
            CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker-7.6.0-v2:29092'
            CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper-7.6.0-v2:2181'
            CONTROL_CENTER_SCHEMA_REGISTRY_URL: http://schema-registry-7.6.0-v2:8081
            CONTROL_CENTER_REPLICATION_FACTOR: 1
            CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
            CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
            CONFLUENT_METRICS_TOPIC_REPLICATION: 1
            PORT: 9021
        volumes:
            - control-center_7.6.0-v2_vol:/var/lib/confluent-control-center/data
    #----------------------------------------------------------------------------------------

networks:
    open_network:
        external: true

volumes:
    zookeeper_7.6.0-v2_vol:
    kafka-7.6.0-v2_vol:
    schema-registry_7.6.0-v2_vol:
    rest-proxy_7.6.0-v2_vol:
    control-center_7.6.0-v2_vol:
